---
title: "Compositional equivalence"
date: "Compiled at `r format(Sys.time(), '%Y-%m-%d %H:%M:%S', tz = 'UTC')` UTC"
output: 
  github_document: default
  html_document:
    toc: true
    toc_depth: 5
    toc_float: true
params:
  name: "06_comp_equivalence" # change if you rename file
---

```{r here, message=FALSE}
here::i_am(paste0(params$name, ".Rmd"), uuid = "312648b4-8c26-4e76-aff7-ab6062b7ba2e")
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(
  dev = c("png", "cairo_pdf"),
  fig.ext = c("png", "pdf"),
  fig.width = 8, 
  fig.height = 5, 
  dpi = 250,
  fig.path = paste0('figures/', params$name, "/comp_equi_"),
  echo = FALSE)
```

```{r packages}
library("conflicted")
```

```{r directories}
# create or *empty* the target directory, used to write this file's data: 
projthis::proj_create_dir_target(params$name, clean = TRUE)

# function to get path to target directory: path_target("sample.csv")
path_target <- projthis::proj_path_target(params$name)

# function to get path to previous data: path_source("00-import", "sample.csv")
path_source <- projthis::proj_path_source(params$name)
```

## Tasks

The first task is ...

## Files written

These files have been written to the target directory, ```r paste0("data/", params$name)```:

```{r list-files-target}
projthis::proj_dir_info(path_target())
```
